### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by chenller** [adham-elarabawy/OpenQuadruped#12]

**Comment by GSERGD** [comment]
I've tried various ways to download. But they all failed.I think the error was caused by a file named \.I think changing the file name can solve this problem. I would like to express my gratitude to the author.

**Comment by GSERGD** [comment]
I've tried various ways to download. But they all failed.I think the error was caused by a file named \\ .I think changing the file name can solve this problem. I would like to express my gratitude to the author.
