### ISSUE TITLE
Parts list link no longer working

### ISSUE THREAD

**Issue by ARingshall** [adham-elarabawy/OpenQuadruped#14]
Hi Adham
great project, just wondering if you have the parts list still available as it appears to have been deleted? 

Cheers
Alex

**Comment by domcross** [comment]
see link "BOM" here: https://github.com/OpenQuadruped/spot_mini_mini/tree/spot/spot_real

or direct link: https://docs.google.com/spreadsheets/d/1Z4y59K8bY3r_442I70xe564zAFuP0pVIFEJ6bNZaCi0/edit?usp=sharing

**Comment by ARingshall** [comment]
Nice one, cheers mate
