### ISSUE TITLE
Integrating with ROS

### ISSUE THREAD

**Issue by adham-elarabawy** [adham-elarabawy/OpenQuadruped#3]
In order to switch to using a ROS infrastructure, there needs to be significant work done on refactoring much of the codebase. It is as follows:
 - [x] Jetson Nano Networking setup
   - [x] autoconnect to laptop's network
   - [x] document connection procedure
 - [x] Install ROS melodic on Jetson Nano
 - [ ] Verify ROS functionality
   - [x] sub & pub to topics using nodes on jetson nano
   - [x] serial comm between jetson nano / teensy
   - [x] sub & pub to topics using nodes on jetson nano / teensy
   - [ ] ~sub & pub to topics using nodes on teensy~
     - Not possible. Teensy can only act as 1 node. 
 - [x] Based on the results of above task, determine proper node layout
   - [x] create diagram (https://github.com/adham-elarabawy/OpenQuadruped/wiki/ROS-Node-Infrastructure)
 - [ ] Refactor codebase
   - [x] Import ros libs in teensy lib dir
   - [x] Implement base ROS init + callback in teensy
   - [x] Test ros joy lib with ds4drv ps4 driver
   - [x] Create custom message for 4 leg poses
   - [x] Header files for custom message on teensy
   - [x] Experiment with ROS ps4 controller packages
   - [x] Minor refactoring for main jetson nano control process. Node-ify it.
   - [ ] Modify LLC c++ code to remove Leg IK from teensy (LLC should accept joint angles, not leg htf vectors).

**Comment by adham-elarabawy** [comment]
All references to "documentation" are referring to the repo wiki.

**Comment by caelinsutch** [comment]
Are you planning on integrating sim?

**Comment by adham-elarabawy** [comment]
Yes, but I'm not sure if I'm going to use Gazebo or pybullet

**Comment by adham-elarabawy** [comment]
I'd like to finish base ROS integration first, then write some unit tests for some of the inverse kinematics classes. Then, sim -> RL.

**Comment by adham-elarabawy** [comment]
Created ROS Node Infrastructure diagram + explanation of control processes. https://github.com/adham-elarabawy/OpenQuadruped/wiki/ROS-Node-Infrastructure

**Comment by caelinsutch** [comment]
> Created ROS Node Infrastructure diagram + explanation of control processes. https://github.com/adham-elarabawy/OpenQuadruped/wiki/ROS-Node-Infrastructure

You didn't link anything

**Comment by adham-elarabawy** [comment]
> > Created ROS Node Infrastructure diagram + explanation of control processes. https://github.com/adham-elarabawy/OpenQuadruped/wiki/ROS-Node-Infrastructure
> 
> You didn't link anything

Hm, on my end it looks like I linked the documentation in the comment you replied to + in the checklist. Is that not showing up for you?

**Comment by caelinsutch** [comment]
@adham-elarabawy Mobile redirected me to the home page, on my desktop it's showing up fine!

**Comment by caelinsutch** [comment]
The package configuration is still pretty non standard, take a look at [this repo](https://github.com/chvmp/champ)
