### ISSUE TITLE
About the pulleys on the 3D model

### ISSUE THREAD

**Issue by takanotume24** [adham-elarabawy/OpenQuadruped#6]
Hi, I'm from the spot_mini_mini repository.
I saw the video on Youtube, and I think it's a great robot, so I'd love to make one myself!

Viewed on https://cad.onshape.com/documents/9d0f96878c54300abf1157ac/w/c9cdf8daa98d8a0d7d50c8d3/e/fa0d7caf0ed2ef46834ecc24, Did you make the pulleys with a 3D printer?
Or do you use a commercial product?

**Comment by adham-elarabawy** [comment]
The pulleys (like 90% of the parts on the quadruped) are 3D printed. They're made to fit 300mm 2GT belts. Please let me know if you have any other questions.
